
-- MySQL Script generated by MySQL Workbench
-- Tue Aug 20 23:21:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(145) NULL,
  `sigla` CHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(145) NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`, `estado_id`),
  INDEX `fk_cidade_estado_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mydb`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL,
  `email` VARCHAR(100) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restaurante` (
  `id` INT NOT NULL,
  `razaoSocial` VARCHAR(150) NULL,
  `nomeFantasia` VARCHAR(150) NULL,
  `endereço` VARCHAR(150) NULL,
  `telefone` VARCHAR(45) NULL,
  `cidade_id` INT NOT NULL,
  `cidade_estado_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cidade_id`, `cidade_estado_id`),
  INDEX `fk_restaurante_cidade1_idx` (`cidade_id` ASC, `cidade_estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_restaurante_cidade1`
    FOREIGN KEY (`cidade_id` , `cidade_estado_id`)
    REFERENCES `mydb`.`cidade` (`id` , `estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(150) NULL,
  `endereco` VARCHAR(100) NULL,
  `telefone` VARCHAR(45) NULL,
  `dataAdmissao` DATE NULL,
  `dataNascimento` DATE NULL,
  `cidade_id` INT NOT NULL,
  `cidade_estado_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `restaurante_id` INT NOT NULL,
  `restaurante_cidade_id` INT NOT NULL,
  `restaurante_cidade_estado_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cidade_id`, `cidade_estado_id`, `usuario_id`, `restaurante_id`, `restaurante_cidade_id`, `restaurante_cidade_estado_id`),
  INDEX `fk_funcionario_cidade1_idx` (`cidade_id` ASC, `cidade_estado_id` ASC) VISIBLE,
  INDEX `fk_funcionario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_funcionario_restaurante1_idx` (`restaurante_id` ASC, `restaurante_cidade_id` ASC, `restaurante_cidade_estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_cidade1`
    FOREIGN KEY (`cidade_id` , `cidade_estado_id`)
    REFERENCES `mydb`.`cidade` (`id` , `estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_restaurante1`
    FOREIGN KEY (`restaurante_id` , `restaurante_cidade_id` , `restaurante_cidade_estado_id`)
    REFERENCES `mydb`.`restaurante` (`id` , `cidade_id` , `cidade_estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `dataNascimento` DATE NULL,
  `genero` CHAR(1) NULL,
  `telefone` VARCHAR(45) NULL,
  `cidade_id` INT NOT NULL,
  `cidade_estado_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cidade_id`, `cidade_estado_id`, `usuario_id`),
  INDEX `fk_cliente_cidade1_idx` (`cidade_id` ASC, `cidade_estado_id` ASC) VISIBLE,
  INDEX `fk_cliente_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_cidade1`
    FOREIGN KEY (`cidade_id` , `cidade_estado_id`)
    REFERENCES `mydb`.`cidade` (`id` , `estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id` INT NOT NULL,
  `rua` VARCHAR(100) NULL,
  `numeroImovel` VARCHAR(10) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` INT NULL,
  `pontoReferencia` VARCHAR(100) NULL,
  `cliente_id` INT NOT NULL,
  `cliente_cidade_id` INT NOT NULL,
  `cliente_cidade_estado_id` INT NOT NULL,
  `cliente_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cliente_id`, `cliente_cidade_id`, `cliente_cidade_estado_id`, `cliente_usuario_id`),
  INDEX `fk_endereco_cliente1_idx` (`cliente_id` ASC, `cliente_cidade_id` ASC, `cliente_cidade_estado_id` ASC, `cliente_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cliente1`
    FOREIGN KEY (`cliente_id` , `cliente_cidade_id` , `cliente_cidade_estado_id` , `cliente_usuario_id`)
    REFERENCES `mydb`.`cliente` (`id` , `cidade_id` , `cidade_estado_id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entregador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entregador` (
  `id` INT NOT NULL,
  `cnh` INT NULL,
  `nome` VARCHAR(150) NULL,
  `endereço` VARCHAR(150) NULL,
  `telefone` VARCHAR(45) NULL,
  `cidade_id` INT NOT NULL,
  `cidade_estado_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cidade_id`, `cidade_estado_id`),
  INDEX `fk_entregador_cidade1_idx` (`cidade_id` ASC, `cidade_estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_entregador_cidade1`
    FOREIGN KEY (`cidade_id` , `cidade_estado_id`)
    REFERENCES `mydb`.`cidade` (`id` , `estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`statusPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`statusPedido` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id` INT NOT NULL,
  `dataPedido` DATE NULL,
  `totalPedido` DECIMAL NULL,
  `statusPedido_id` INT NOT NULL,
  `entregador_id` INT NOT NULL,
  `entregador_cidade_id` INT NOT NULL,
  `entregador_cidade_estado_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `cliente_cidade_id` INT NOT NULL,
  `cliente_cidade_estado_id` INT NOT NULL,
  `cliente_usuario_id` INT NOT NULL,
  `restaurante_id` INT NOT NULL,
  `restaurante_cidade_id` INT NOT NULL,
  `restaurante_cidade_estado_id` INT NOT NULL,
  PRIMARY KEY (`id`, `statusPedido_id`, `entregador_id`, `entregador_cidade_id`, `entregador_cidade_estado_id`, `cliente_id`, `cliente_cidade_id`, `cliente_cidade_estado_id`, `cliente_usuario_id`, `restaurante_id`, `restaurante_cidade_id`, `restaurante_cidade_estado_id`),
  INDEX `fk_pedido_statusPedido1_idx` (`statusPedido_id` ASC) VISIBLE,
  INDEX `fk_pedido_entregador1_idx` (`entregador_id` ASC, `entregador_cidade_id` ASC, `entregador_cidade_estado_id` ASC) VISIBLE,
  INDEX `fk_pedido_cliente1_idx` (`cliente_id` ASC, `cliente_cidade_id` ASC, `cliente_cidade_estado_id` ASC, `cliente_usuario_id` ASC) VISIBLE,
  INDEX `fk_pedido_restaurante1_idx` (`restaurante_id` ASC, `restaurante_cidade_id` ASC, `restaurante_cidade_estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_statusPedido1`
    FOREIGN KEY (`statusPedido_id`)
    REFERENCES `mydb`.`statusPedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_entregador1`
    FOREIGN KEY (`entregador_id` , `entregador_cidade_id` , `entregador_cidade_estado_id`)
    REFERENCES `mydb`.`entregador` (`id` , `cidade_id` , `cidade_estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_id` , `cliente_cidade_id` , `cliente_cidade_estado_id` , `cliente_usuario_id`)
    REFERENCES `mydb`.`cliente` (`id` , `cidade_id` , `cidade_estado_id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_restaurante1`
    FOREIGN KEY (`restaurante_id` , `restaurante_cidade_id` , `restaurante_cidade_estado_id`)
    REFERENCES `mydb`.`restaurante` (`id` , `cidade_id` , `cidade_estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoProduto` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `valorUnitario` DECIMAL NULL,
  `estoque` INT NULL,
  `tipoProduto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipoProduto_id`),
  INDEX `fk_produto_tipoProduto1_idx` (`tipoProduto_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_tipoProduto1`
    FOREIGN KEY (`tipoProduto_id`)
    REFERENCES `mydb`.`tipoProduto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido_has_produto` (
  `quantidadeProduto` INT NULL,
  `valorUnitario` DECIMAL NULL,
  `desconto` DECIMAL NULL,
  `pedido_id` INT NOT NULL,
  `pedido_statusPedido_id` INT NOT NULL,
  `pedido_entregador_id` INT NOT NULL,
  `pedido_entregador_cidade_id` INT NOT NULL,
  `pedido_entregador_cidade_estado_id` INT NOT NULL,
  `pedido_cliente_id` INT NOT NULL,
  `pedido_cliente_cidade_id` INT NOT NULL,
  `pedido_cliente_cidade_estado_id` INT NOT NULL,
  `pedido_cliente_usuario_id` INT NOT NULL,
  `pedido_restaurante_id` INT NOT NULL,
  `pedido_restaurante_cidade_id` INT NOT NULL,
  `pedido_restaurante_cidade_estado_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `produto_tipoProduto_id` INT NOT NULL,
  PRIMARY KEY (`pedido_id`, `pedido_statusPedido_id`, `pedido_entregador_id`, `pedido_entregador_cidade_id`, `pedido_entregador_cidade_estado_id`, `pedido_cliente_id`, `pedido_cliente_cidade_id`, `pedido_cliente_cidade_estado_id`, `pedido_cliente_usuario_id`, `pedido_restaurante_id`, `pedido_restaurante_cidade_id`, `pedido_restaurante_cidade_estado_id`, `produto_id`, `produto_tipoProduto_id`),
  INDEX `fk_pedido_has_produto_produto1_idx` (`produto_id` ASC, `produto_tipoProduto_id` ASC) VISIBLE,
  INDEX `fk_pedido_has_produto_pedido1_idx` (`pedido_id` ASC, `pedido_statusPedido_id` ASC, `pedido_entregador_id` ASC, `pedido_entregador_cidade_id` ASC, `pedido_entregador_cidade_estado_id` ASC, `pedido_cliente_id` ASC, `pedido_cliente_cidade_id` ASC, `pedido_cliente_cidade_estado_id` ASC, `pedido_cliente_usuario_id` ASC, `pedido_restaurante_id` ASC, `pedido_restaurante_cidade_id` ASC, `pedido_restaurante_cidade_estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_produto_pedido1`
    FOREIGN KEY (`pedido_id` , `pedido_statusPedido_id` , `pedido_entregador_id` , `pedido_entregador_cidade_id` , `pedido_entregador_cidade_estado_id` , `pedido_cliente_id` , `pedido_cliente_cidade_id` , `pedido_cliente_cidade_estado_id` , `pedido_cliente_usuario_id` , `pedido_restaurante_id` , `pedido_restaurante_cidade_id` , `pedido_restaurante_cidade_estado_id`)
    REFERENCES `mydb`.`pedido` (`id` , `statusPedido_id` , `entregador_id` , `entregador_cidade_id` , `entregador_cidade_estado_id` , `cliente_id` , `cliente_cidade_id` , `cliente_cidade_estado_id` , `cliente_usuario_id` , `restaurante_id` , `restaurante_cidade_id` , `restaurante_cidade_estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_produto_produto1`
    FOREIGN KEY (`produto_id` , `produto_tipoProduto_id`)
    REFERENCES `mydb`.`produto` (`id` , `tipoProduto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
